<?php


$girls = [
  [
    'name' => 'かや',
    'age' => '25',
    'time' => '9:00~15:00',
    'tall' => '155',
    'bust' => '85(D)',
    'waist' => '55',
    'hip' => '85',
    'img' => '',
    'nominal' => '4000',
    'newface' => true,
    'sun' => true,
    'mon' => false,
    'tue' => true,
    'wed' => false,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'もう',
    'age' => '22',
    'time' => '18:00~23:00',
    'tall' => '157',
    'bust' => '84(C)',
    'waist' => '55',
    'hip' => '84',
    'img' => '13',
    'nominal' => '3000',
    'newface' => false,
    'sun' => false,
    'mon' => true,
    'tue' => false,
    'wed' => false,
    'thu' => true,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'れいこ',
    'age' => '20',
    'time' => '22:00~4:00',
    'tall' => '160',
    'bust' => '84(C)',
    'waist' => '54',
    'hip' => '83',
    'img' => '',
    'nominal' => '2000',
    'newface' => true,
    'sun' => true,
    'mon' => false,
    'tue' => false,
    'wed' => true,
    'thu' => false,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'るる',
    'age' => '20',
    'time' => '14:00~20:00',
    'tall' => '148',
    'bust' => '83(B)',
    'waist' => '54',
    'hip' => '83',
    'img' => '14',
    'nominal' => '3000',
    'newface' => false,
    'sun' => false,
    'mon' => true,
    'tue' => true,
    'wed' => false,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'のぞみ',
    'age' => '23',
    'time' => '21:00~3:00',
    'tall' => '157',
    'bust' => '85(D)',
    'waist' => '54',
    'hip' => '84',
    'img' => '9',
    'nominal' => '4000',
    'newface' => false,
    'sun' => true,
    'mon' => false,
    'tue' => false,
    'wed' => false,
    'thu' => true,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'なな',
    'age' => '20',
    'time' => '10:00~15:00',
    'tall' => '160',
    'bust' => '83(C)',
    'waist' => '55',
    'hip' => '82',
    'img' => '11',
    'nominal' => '2000',
    'newface' => true,
    'sun' => false,
    'mon' => true,
    'tue' => false,
    'wed' => true,
    'thu' => false,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'みみ',
    'age' => '20',
    'time' => '18:00~0:00',
    'tall' => '164',
    'bust' => '84(D)',
    'waist' => '54',
    'hip' => '83',
    'img' => '',
    'nominal' => '2000',
    'newface' => true,
    'sun' => true,
    'mon' => false,
    'tue' => true,
    'wed' => false,
    'thu' => true,
    'fri' => false,
    'sat' => false,
  ],
  [
    'name' => 'メル',
    'age' => '21',
    'time' => '23:00~3:00',
    'tall' => '158',
    'bust' => '82(B)',
    'waist' => '54',
    'hip' => '84',
    'img' => '',
    'nominal' => '4000',
    'newface' => true,
    'sun' => false,
    'mon' => false,
    'tue' => true,
    'wed' => true,
    'thu' => false,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'しずく',
    'age' => '23',
    'time' => '9:00~14:00',
    'tall' => '152',
    'bust' => '85(D)',
    'waist' => '55',
    'hip' => '83',
    'img' => '',
    'nominal' => '3000',
    'newface' => true,
    'sun' => true,
    'mon' => true,
    'tue' => false,
    'wed' => false,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'りあ',
    'age' => '22',
    'time' => '16:00~22:00',
    'tall' => '157',
    'bust' => '84(C)',
    'waist' => '54',
    'hip' => '82',
    'img' => '15',
    'nominal' => '3000',
    'newface' => false,
    'sun' => false,
    'mon' => true,
    'tue' => false,
    'wed' => false,
    'thu' => true,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'いるみ',
    'age' => '26',
    'time' => '12:00~18:00',
    'tall' => '151',
    'bust' => '89(F)',
    'waist' => '56',
    'hip' => '88',
    'img' => '0',
    'nominal' => '3000',
    'newface' => true,
    'sun' => true,
    'mon' => false,
    'tue' => true,
    'wed' => false,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'さな',
    'age' => '26',
    'time' => '20:00~2:00',
    'tall' => '153',
    'bust' => '87(D)',
    'waist' => '55',
    'hip' => '84',
    'img' => '8',
    'nominal' => '5000',
    'newface' => false,
    'sun' => false,
    'mon' => false,
    'tue' => true,
    'wed' => true,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'けい',
    'age' => '20',
    'time' => '10:00~15:00',
    'tall' => '157',
    'bust' => '86(D)',
    'waist' => '55',
    'hip' => '83',
    'img' => '12',
    'nominal' => '5000',
    'newface' => false,
    'sun' => true,
    'mon' => true,
    'tue' => false,
    'wed' => false,
    'thu' => true,
    'fri' => false,
    'sat' => false,
  ],
  [
    'name' => 'こう',
    'age' => '22',
    'time' => '13:00~18:00',
    'tall' => '164',
    'bust' => '82(B)',
    'waist' => '54',
    'hip' => '83',
    'img' => '',
    'nominal' => '2000',
    'newface' => true,
    'sun' => false,
    'mon' => true,
    'tue' => false,
    'wed' => true,
    'thu' => false,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'ゆうき',
    'age' => '23',
    'time' => '22:00~4:00',
    'tall' => '155',
    'bust' => '90(F)',
    'waist' => '54',
    'hip' => '86',
    'img' => '',
    'nominal' => '2000',
    'newface' => false,
    'sun' => true,
    'mon' => false,
    'tue' => false,
    'wed' => true,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'ぽこ',
    'age' => '21',
    'time' => '11:00~17:00',
    'tall' => '149',
    'bust' => '84(C)',
    'waist' => '54',
    'hip' => '84',
    'img' => '10',
    'nominal' => '3000',
    'newface' => false,
    'sun' => false,
    'mon' => false,
    'tue' => true,
    'wed' => false,
    'thu' => true,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'こうき',
    'age' => '26',
    'time' => '15:00~21:00',
    'tall' => '162',
    'bust' => '85(D)',
    'waist' => '60',
    'hip' => '85',
    'img' => '5',
    'nominal' => '5000',
    'newface' => false,
    'sun' => true,
    'mon' => false,
    'tue' => true,
    'wed' => false,
    'thu' => false,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'まつり',
    'age' => '23',
    'time' => '11:00~17:00',
    'tall' => '158',
    'bust' => '86(E)',
    'waist' => '58',
    'hip' => '86',
    'img' => '',
    'nominal' => '3000',
    'newface' => false,
    'sun' => false,
    'mon' => true,
    'tue' => false,
    'wed' => true,
    'thu' => true,
    'fri' => false,
    'sat' => false,
  ],
  [
    'name' => 'たまき',
    'age' => '25',
    'time' => '19:00~0:00',
    'tall' => '158',
    'bust' => '80(B)',
    'waist' => '54',
    'hip' => '82',
    'img' => '4',
    'nominal' => '2000',
    'newface' => false,
    'sun' => true,
    'mon' => false,
    'tue' => false,
    'wed' => false,
    'thu' => true,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'みちる',
    'age' => '22',
    'time' => '9:00~15:00',
    'tall' => '155',
    'bust' => '83(B)',
    'waist' => '58',
    'hip' => '80',
    'img' => '',
    'nominal' => '4000',
    'newface' => true,
    'sun' => false,
    'mon' => true,
    'tue' => true,
    'wed' => false,
    'thu' => false,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'ほのか',
    'age' => '21',
    'time' => '0:00~4:00',
    'tall' => '170',
    'bust' => '82(B)',
    'waist' => '62',
    'hip' => '86',
    'img' => '',
    'nominal' => '2000',
    'newface' => false,
    'sun' => true,
    'mon' => false,
    'tue' => false,
    'wed' => true,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'えり',
    'age' => '24',
    'time' => '17:00~23:00',
    'tall' => '162',
    'bust' => '83(C)',
    'waist' => '58',
    'hip' => '80',
    'img' => '',
    'nominal' => '3000',
    'newface' => true,
    'sun' => false,
    'mon' => true,
    'tue' => false,
    'wed' => false,
    'thu' => true,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'りり',
    'age' => '21',
    'time' => '11:00~16:00',
    'tall' => '159',
    'bust' => '82(B)',
    'waist' => '56',
    'hip' => '80',
    'img' => '1',
    'nominal' => '3000',
    'newface' => false,
    'sun' => true,
    'mon' => false,
    'tue' => true,
    'wed' => false,
    'thu' => true,
    'fri' => false,
    'sat' => false,
  ],
  [
    'name' => 'ふうか',
    'age' => '24',
    'time' => '21:00~2:00',
    'tall' => '161',
    'bust' => '85(D)',
    'waist' => '55',
    'hip' => '82',
    'img' => '',
    'nominal' => '3000',
    'newface' => false,
    'sun' => false,
    'mon' => false,
    'tue' => true,
    'wed' => true,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'アリエル',
    'age' => '22',
    'time' => '12:00~17:00',
    'tall' => '161',
    'bust' => '85(D)',
    'waist' => '55',
    'hip' => '82',
    'img' => '7',
    'nominal' => '5000',
    'newface' => false,
    'sun' => true,
    'mon' => true,
    'tue' => false,
    'wed' => false,
    'thu' => false,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'える',
    'age' => '23',
    'time' => '12:00~18:00',
    'tall' => '160',
    'bust' => '83(B)',
    'waist' => '54',
    'hip' => '80',
    'img' => '',
    'nominal' => '3000',
    'newface' => true,
    'sun' => false,
    'mon' => true,
    'tue' => false,
    'wed' => true,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'そう',
    'age' => '28',
    'time' => '14:00~19:00',
    'tall' => '162',
    'bust' => '82(B)',
    'waist' => '56',
    'hip' => '84',
    'img' => '6',
    'nominal' => '2000',
    'newface' => false,
    'sun' => true,
    'mon' => false,
    'tue' => false,
    'wed' => false,
    'thu' => true,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'カエラ',
    'age' => '21',
    'time' => '22:00~3:00',
    'tall' => '157',
    'bust' => '86(D)',
    'waist' => '60',
    'hip' => '88',
    'img' => '',
    'nominal' => '4000',
    'newface' => true,
    'sun' => false,
    'mon' => false,
    'tue' => true,
    'wed' => true,
    'thu' => false,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'シエル',
    'age' => '21',
    'time' => '18:00~0:00',
    'tall' => '160',
    'bust' => '88(G)',
    'waist' => '58',
    'hip' => '85',
    'img' => '',
    'nominal' => '5000',
    'newface' => true,
    'sun' => true,
    'mon' => false,
    'tue' => true,
    'wed' => false,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
  [
    'name' => 'シエラ',
    'age' => '22',
    'time' => '9:00~14:00',
    'tall' => '160',
    'bust' => '80(B)',
    'waist' => '54',
    'hip' => '80',
    'img' => '2',
    'nominal' => '2000',
    'newface' => false,
    'sun' => false,
    'mon' => true,
    'tue' => false,
    'wed' => true,
    'thu' => true,
    'fri' => false,
    'sat' => false,
  ],
  [
    'name' => 'るい',
    'age' => '26',
    'time' => '23:00~4:00',
    'tall' => '150',
    'bust' => '80(B)',
    'waist' => '54',
    'hip' => '82',
    'img' => '3',
    'nominal' => '2000',
    'newface' => false,
    'sun' => true,
    'mon' => false,
    'tue' => false,
    'wed' => true,
    'thu' => false,
    'fri' => false,
    'sat' => true,
  ],
  [
    'name' => 'あみ',
    'age' => '21',
    'time' => '15:00~20:00',
    'tall' => '160',
    'bust' => '88(G)',
    'waist' => '58',
    'hip' => '85',
    'img' => '',
    'nominal' => '5000',
    'newface' => true,
    'sun' => false,
    'mon' => true,
    'tue' => true,
    'wed' => false,
    'thu' => false,
    'fri' => true,
    'sat' => false,
  ],
];
